### ISSUE TITLE
IR hardware

### ISSUE THREAD

**Issue by jxr041100** [YutaItoh/3D-Eye-Tracker#23]
what kinds of IR hardware you are using ? currently I run your code on my window PC, it will use the webcam, it could not provide the correct result.  Your input should be eye region, right?

**Comment by NuncObdurat** [comment]
Hi jxr. This API is designed for near-eye cameras and not for webcameras. We recommend the pupil-labs cameras since they are relatively inexpensive and work well with our algorithm. You can purchase a set here: https://pupil-labs.com/pupil/

Any near-eye camera with active IR illumination should work though.
