### ISSUE TITLE
Possibility of c# solution

### ISSUE THREAD

**Issue by edgar-mtz-e** [YutaItoh/3D-Eye-Tracker#8]
I have tested the solution in c++ it works nicely, however I would like to do some C# programming, is there a possibility to create this as a library (compile it to a static library (.lib)) and then use it in C++/CLI wrapper ?
The issue would how to create the C++/CLI wrapper, As I have seen some complex opencv datatypes as result of some of the computations...

Do you think it's easier to translate c++ code to c# and then use opencvsharp or something similar?

**Comment by jason01234** [comment]
Hi Edgar, 

What is your goal with the C# programming? Are you just more comfortable with C# or do you want to use eye tracking in something like Unity? 

My first impression is that certain parts could be compiled to .libs and used with wrappers, but converting the whole project would take significant effort. 

Best,
Jason

**Comment by edgar-mtz-e** [comment]
Hi Jason, actually both I know C# but not too much C++, and I would like to use the eye tracking in some research I am doing,  because your code is the best and fastest I´ve seen so far...

Do you think the code would be as efficient in C# as in C++?
Maybe I could try to convert some code to C# and other code compile it as a lib.
Or what would you suggest.

Thanks for your soon response

**Comment by jason01234** [comment]
Hi Edgar, 

We're happy to hear that. 

If the wrapper is properly written, there shouldn't be a big difference in performance if you use it in C#. Compiling to a lib is also a possibility, though you need to be careful with memory/thread management.  
Though written for Unity, this tutorial may be helpful: 
http://ericeastwood.com/blog/17/unity-and-dlls-c-managed-and-c-unmanaged

I also have another recommendation if you just need the data:
One very easy way to pass data from C++ to C# for prototyping/research is to constantly write data to a single line of a text file. Write directly from C++ every frame and read that line into C# every time you need data. The constant read/write operations only takes a few milliseconds (since the file is typically cached) and you don't have to write a complex wrapper class. 

If you want to modify or improve our code, then learning C++ is probably a good idea. 

Best,
Jason
